apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lesma
  namespace: lesma
  labels:
    app: lesma
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "31536000"
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: lesma.czcx.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lesma
                port:
                  number: 80
  tls:
    - secretName: lesma-tls-prod-cert
      hosts:
        - lesma.czcx.cc