apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monica
  namespace: monica
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - secretName: monica-internal-tls-prod-cert
      hosts:
        - monica.internal.czcx.cc
  rules:
    - host: monica.internal.czcx.cc
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: monica
                port:
                  number: 80
